### ISSUE TITLE
Upload tarballs to sourceforge

### ISSUE THREAD

**Issue by poletti-marco** [afrimberger/okularplugin#7]
During the review of the Gentoo ebuild, hasufell pointed out that uploading the tarball to some other site would be nice. He suggested sourceforge.
Can you get a sourceforge account (if you don't have one already) and upload the 1.0.1 tarball there?
The current tarball is at:
https://github.com/afrimberger/okularplugin/archive/v1.0.1.tar.gz

It'd be better if you rename it to okularplugin-1.0.1.tar.gz in sourceforge.

**Comment by afrimberger** [comment]
Here you are: https://sourceforge.net/projects/okularplugin/
From now on I'll upload releases to sf, too.
